package com.nekoscape.android.ntc.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig networkTypeDaoConfig;
    private final DaoConfig communicationDaoConfig;
    private final DaoConfig hourDaoConfig;

    private final NetworkTypeDao networkTypeDao;
    private final CommunicationDao communicationDao;
    private final HourDao hourDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        networkTypeDaoConfig = daoConfigMap.get(NetworkTypeDao.class).clone();
        networkTypeDaoConfig.initIdentityScope(type);

        communicationDaoConfig = daoConfigMap.get(CommunicationDao.class).clone();
        communicationDaoConfig.initIdentityScope(type);

        hourDaoConfig = daoConfigMap.get(HourDao.class).clone();
        hourDaoConfig.initIdentityScope(type);

        networkTypeDao = new NetworkTypeDao(networkTypeDaoConfig, this);
        communicationDao = new CommunicationDao(communicationDaoConfig, this);
        hourDao = new HourDao(hourDaoConfig, this);

        registerDao(NetworkType.class, networkTypeDao);
        registerDao(Communication.class, communicationDao);
        registerDao(Hour.class, hourDao);
    }

    public void clear() {
        networkTypeDaoConfig.getIdentityScope().clear();
        communicationDaoConfig.getIdentityScope().clear();
        hourDaoConfig.getIdentityScope().clear();
    }

    public NetworkTypeDao getNetworkTypeDao() {
        return networkTypeDao;
    }

    public CommunicationDao getCommunicationDao() {
        return communicationDao;
    }

    public HourDao getHourDao() {
        return hourDao;
    }

}
