package com.nekoscape.android.ntc.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table NetworkTypeTable.
 */
public class NetworkType {

    private Long id;
    private Integer type;
    private Integer subtype;
    private String ssid;

    public NetworkType() {
    }

    public NetworkType(Long id) {
        this.id = id;
    }

    public NetworkType(Long id, Integer type, Integer subtype, String ssid) {
        this.id = id;
        this.type = type;
        this.subtype = subtype;
        this.ssid = ssid;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getSubtype() {
        return subtype;
    }

    public void setSubtype(Integer subtype) {
        this.subtype = subtype;
    }

    public String getSsid() {
        return ssid;
    }

    public void setSsid(String ssid) {
        this.ssid = ssid;
    }

}
